### ISSUE TITLE
Recommended representation for sgRNA/dCas9 interaction

### ISSUE THREAD

**Issue by Gonza10V** [SynBioDex/SBOL-visual#110]
Which one is a better representation of the process:

We used to do this:

<img width="681" alt="Screen Shot 2020-10-13 at 13 01 20" src="https://user-images.githubusercontent.com/35148159/95888098-0c9f1480-0d57-11eb-92df-8d372b670920.png">

but now I think this could be more accurate:

<img width="726" alt="Screen Shot 2020-10-13 at 13 00 14" src="https://user-images.githubusercontent.com/35148159/95888156-1d4f8a80-0d57-11eb-8815-6b58256bb99c.png">

It just need the interaction node Process (https://github.com/SynBioDex/SBOL-visual/tree/master/Glyphs/InteractionNodes/process) in the joint between the sgRNA and dCas9. I draw the images in SBOLcanvas and drop an issue asking for that interaction nodes feature (https://github.com/SynBioDex/SBOLCanvas/issues/135)

Please give me any feedback from they way to add issues or the workflow if Im not following something.

**Comment by jakebeal** [comment]
Yes, it does definitely need the interaction node at the junction.  

Once that is there, however, the second is correct while the first is problematic.  The reason is the interaction node, which is an SBO process (https://www.ebi.ac.uk/sbo/main/SBO:0000375) whose inputs are its reactants (SBO:0000010 Reactant). Coding sequences and ncRNA aren't reactants, though. Instead, their products are reactanges.  Thus, the semantics of the top version aren't currently supported.

It's possible we could end up with a semantics that supports implicit nodes, but that's still being worked out on SEP V018 (#73)

**Comment by Gonza10V** [comment]
![dCas9-sgRNA-TMAINU](https://user-images.githubusercontent.com/35148159/95916121-8f879580-0d7e-11eb-846d-a24aea1bf30a.png)

**Comment by Gonza10V** [comment]
Sorry for the previous close and reopen I miss-clicked. I just wanted to share my current implementation that I think is according to SBOL3, if it is can work as example.
![dCas9-sgRNA-TMAINU](https://user-images.githubusercontent.com/35148159/95916534-2bb19c80-0d7f-11eb-90e0-85448e9f4509.png)

**Comment by jakebeal** [comment]
@Gonza10V This is correct, but there are a few best-practice recommendations in the specification that would improve it further:

- pLacI and other promoters should not overlap with the ribosome entry sites unless their sequences actually overlap.
- The Process interaction node should be replaced by the more specific circular Association node, to represent the non-covalent binding.
- The reverse complement sequences should be flipped upside down on the opposite side of the strand.

You might also want to consider whether to show the genetic production of LacI and TetR from their CDSes, but that's optional.  You might, however, want to change the color for lacI/LacI/IPTG to look less like venus.

**Comment by Gonza10V** [comment]
Thanks for the feedback @jakebeal ! 

- Yes can be confusing to have the promoter overlapping the RES.

- I have a doubt now reviewing the used Process interaction node because of its [prototypical example](https://github.com/SynBioDex/SBOL-visual/tree/master/Glyphs/InteractionNodes/process#prototypical-example) that now I realize is the same in Association [prototypical example](https://github.com/SynBioDex/SBOL-visual/tree/master/Glyphs/InteractionNodes/association#prototypical-example). This can be confusing for more people should I make an issue about that?

- About flip the reverse complement sequences, that will be hard in the sense that other authors did not like it at all. Is the change in direction still valid but not recommended?

**Comment by jakebeal** [comment]
1. Yes, please make an issue for differentiating the Process example. We can use some other form of reaction instead.
2. Yes, keeping the reverse complement is still valid, just not recommended (i.e., SHOULD rather than MUST, per section 5.2.2 and Figure 10 in the specification)

**Comment by shyambhakta** [comment]
It's common to want to simplify an entire gene as a single glyph: in the diagrams above Kanᴿ and Carᴿ (kanamycin and carbenicillin resistance genes) are shown as CDS arrows. I myself like to use the CDS glyph to represent constitutive resistance  and transcription factor genes for which inclusion of more detailed promoter, RBS, and terminator glyphs makes for undesired clutter. Yet resistance is a phenotype, so can't technically be the label for _just_ a CDS, which would have to have CDS names, _e.g._, _aphA1_/_nptI_/_aphA2_/_nptII_ or _bla_ for these resistance genes. But because these CDS names are less familiar, it's preferable to write the resistance phenotype. This extends to transcription factors, _e.g._ _lacI_^q which is a stronger promoter mutant of the wild-type _lacI_ gene, and thus cannot describe just a CDS.

So what is the recommendation for a glyph of an entire gene, with it's tx/tl initiation/termination elements? Perhaps this should be a new issue if not already described. Some people write the gene in a box instead of an arrow, but this isn't a general solution as gene direction is still useful to describe, hence the use of the CDS glyph. Also, I'm not sure such genes necessary qualify as engineered regions; they're often natural, hence wanting to abstract into a single gene in the same way the many genes with distinct promoters, CDSs, ncRNAs, etc mediating replication origin function are abstracted into a single origin glyph.

An aside: I like to use the American Society of Microbiology's proscribed abbreviations for antibiotics / resistances:
https://aac.asm.org/content/abbreviations-and-conventions

**Comment by jakebeal** [comment]
@shyambhakta In mammalian system engineering, I often just don't see the ribosome entry site and terminator represented at all.  Given the differences in eukaryotic transcription, it seems they are often taken as implicit by the presence of a CDS.  We are never required to draw glyphs for every base, so why not just omit those portions if they aren't of interest?

**Comment by shyambhakta** [comment]
The issue isn't the possibility of glyph omission; it's that a whole gene/locus name be placed on / assigned to a CDS glyph when not describing just the CDS alone but rather more parts than the CDS, even more than one gene's worth if an operon.

For example, an arabinose transcriptional activator + transporter operon _araCE_  may popularly be represented by just a single CDS glyph labeled _ara_ or _araCE_. It's not clear that an SBOL CDS glyph can be used more broadly for such genes, gene clusters, loci, some described by phenotype like the resistance genes I mentioned earlier, which can't impart resistance/other functions as just a CDS. I think it needs to be made explicit if it's somehow already permitted, because I felt like I was willfully violating SBOL when choosing to do so, despite it being common in the literature.

Another case: I use a native cytochrome C maturation gene cluster cloned into a plasmid. But instead of taking a bunch of space with eight CDSs in order labeled _ccmA_ _ccmB_ _ccmC_ _ccmD_ _ccmE_ _ccmF_ _ccmG_ _ccmH_, I and others in the literature simplify it to (the equivalent of) a single CDS glyph labeled _ccm_ which encapsulates the whole operon / gene cluster, from promoter to terminator.

Another example: sets of plasmid partitioning genes used to stabilize plasmid inheritance are often named with the prefix _par_, and their operon(s) (_e.g._ _parABCD_) and their associated promoters/terminators are often simplified to the equivalent of just one CDS glyph labelled _par_, in the primary direction of transcription if there is one.

These sort of common and popular usage cases to me clearly violate the specs of the CDS glyph, which show associated with only **CDS** [SO:0000316:](http://www.sequenceontology.org/browser/current_release/term/SO:0000316) _A contiguous sequence which begins with, and includes, a start codon and ends with, and includes, a stop codon._ The far, far-broader term "gene" is the proposition for what the CDS glyph is also describing in these examples, **gene** [SO:0000704](http://www.sequenceontology.org/browser/current_release/term/SO:0000704) _A region (or regions) that includes all of the sequence elements necessary to encode a functional transcript. A gene may include regulatory regions, transcribed regions and/or other functional sequence regions._ Its children include gene_with_polycistronic_transcript and gene_cassette, and so may cover the examples above, though the usage encompassing multiple genes in multiple operons/directions would require another level up, **gene_group** [SO:0005855](http://www.sequenceontology.org/browser/current_release/term/SO:0005855)**, _A collection of related genes._

A dual-use of the CDS glyph for both a CDS and entire gene cluster is seemingly contradictory, and I'd expect contention on the matter if the consensus is to allow it. And if not, the design of a new gene / gene cluster glyph attempting to replace the traditional could also be contentious. 

By the way, I assumed RBSs are perceived to be a bacterial feature, given the lack of necessity of sequence-specific association of ribosomes to mammalian mRNA 5′ UTRs and a Kozak sequence, rather, mostly by 5′ mRNA cap-association and scanning to a start codon.

**Comment by jakebeal** [comment]
I think the potential to address this by expanding the set of associated SO terms is a good one.  Can you please open a specific issue for discussion of this?

**Comment by jakebeal** [comment]
@Gonza10V Are there still questions open that you want to address regarding this specific issue, or can it be closed in favor of the new issues spun out from it?

**Comment by Gonza10V** [comment]
Thanks @shyambhakta for the proscribed abbreviations for antibiotics / resistances I will implement it, they need the R super index? I usually add it to whiteboard discussions but I dont know if should be added in paper figures.

<img width="1274" alt="Screen Shot 2020-10-14 at 23 38 53" src="https://user-images.githubusercontent.com/35148159/96070378-795d0080-0e76-11eb-8ba3-6774d7e84a3e.png">

@jakebeal This is my latest implementation of the figure and my despite the problems with sequence overlapping and reverse complement display of parts it should be ok, but now the Association node is similar to the origin of replication glyph, is that a problem? I made it smaller and all the interactions in gray to distinct between them. Should be recommended to show interactions in other colors or black is the recommended?

I liked the point that makes @shyambhakta about the resistances and how will be the best form to represent genes or transcriptional units without show all components. We opt for the arrow but that is the second glyph of CDS that as you said is not the correct form to represent a whole gene or gene cassette.

**Comment by shyambhakta** [comment]
Phenotypes are systematically written with only an initial capital letter, so Kanᴿ and Carᴿ/Ampᴿ.
The ASM abbreviations are for the antibiotics alone, which I still don't like to write in all-caps; draws unnecessary attention I feel.
Also, I'd prefer replication origins being labeled; gives an idea as to the gene dosage.

**Comment by Gonza10V** [comment]
I think we discuss the corresponding to this topic, now we will see the issues generated by this topic. Thanks a lot @jakebeal  and @shyambhakta .
