### ISSUE TITLE
Automate generation of latex examples appendix into webpage material

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#121]
The appendix of examples in the back of the specification would be good to share on the website as well as examples. One way to do this and maintain it would be to automate generation of webpage materials from the LaTeX source of https://github.com/SynBioDex/SBOL-visual/blob/master/specification/apdx-examples.tex

**Comment by jamesscottbrown** [comment]
I think it would be cleaner to have a separate CSV or JSON file that lists (filename, caption, sbol-version) triples, and a script that uses this to automatically generate both the `.tex` file for the spec and a `.html` file for the webpage.

Parsing the LaTeX seems like a kludge, and whilst something like Pandoc could convert it to HTML the change bar macros could be a hassle to deal with.

(Unless you meant just building this appendix as a separate PDF, rather than converting to HTML - which should be easy but be slightly less well integrated into the website)

**Comment by Fontanapink** [comment]
I think hugo already has a latex parser for websites.

**Comment by jamesscottbrown** [comment]
This is now implemented, with the caveat that the LaTeX figure references (e.g, `\ref{f:apdx:exa1}`) in captions are not being converted.
