### ISSUE TITLE
rebuild_glyphs.py command path fails on Apple

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#138]
On my Mac, the markdown-pdf comment in rebuild_glyphs.py failed with the following:

`sh: /Users/jakebeal/projects/SBOL/SBOL-visual/node_modules/markdown-pdf/bin/markdown-pdf: No such file or directory`

This is because it was trying to use a local rather than installed command.  I fixed this with the following replacement:
```
+# cmd_path = os.path.abspath(os.path.join(script_dir, os.pardir, "node_modules", "markdown-pdf", "bin", "markdown-pdf"))
+cmd_path = "markdown-pdf"

```

I do not know if this is a generalizable fix, so I am not checking it in, but reporting it for consideration.

**Comment by jamesscottbrown** [comment]
This is due to which install command is used, rather than which OS it is run on.

The Python script works if markdown-pdf was installed locally (`npm install markdown-pdf`), rather than globally (`npm install -g markdown pdf`).

If the python script is changed to use a globally installed markdown-pdf binary, then the install command in `.github/workflows/main.yml` would need to be updated accordingly.

On my Ubuntu machine, permissions problems prevented me from installing it globally (though this worked inside a Ubuntu Docker container).

**Comment by jakebeal** [comment]
I think the README needs to be changed, then on two accounts:

1. If somebody already has markdown-pdf installed on their machine (as I did), then it's easy to get confused about the dependency.
2. The current README ends up installing locally inside of `scripts`, rather than at the top level, which is what the script is expecting.

**Comment by jamesscottbrown** [comment]
I think this is now resolved.
