### ISSUE TITLE
SEP V009: Engineered Region vs. Composite

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#16]
# SEP V009: Engineered Region vs. Composite

| SEP | <leave empty> |
| --- | --- |
| **Authors** | Jacob Beal (jakebeal@ieee.org), Chris Myers, John Sexton |
| **Editor** | <leave empty> |
| **Type** | Specification |
| **SBOL Visual Version** | 1.1 |
| **Status** | Draft |
| **Created** | 7-Oct-2017 |
| **Last modified** | Never |

## Abstract

This SEP proposes to split Engineered Region from Composite.

## 1. Rationale <a name="rationale"></a>

The Engineered Region SO term (SO:0000804) currently assigned to the Composite glyph does not actually describe composite parts: some engineered regions are not meaningfully composites, and some multi-element composites are better described by terms not covered by Engineered Region (e.g., a double terminator, or an evolved gene cluster).  

This SEP thus proposes to split the two terms, giving Engineered Region the Rectangle glyph. The rectangle will also be eventually removed from Unspecified.

### Engineered Region

Associated SO term: SO:0000804 Engineered Region

Glyph: Rectangle

### Composite
The Composite glyph will no longer have a specific SO term. Instead, there will be the following note:

*Composite does not have an associated SO term, as it merely links a base glyph (with its own SO term) to a sub-diagram (comprising glyphs with their own associated SO terms).*

The Rectangle glyph will no longer be an alternative for Composite.

### Unspecified

The Rectangle alternative will be deprecated and given RECOMMEND NOT status for Unspecified in SBOL Visual 1.1, then removed entirely in SBOL Visual 2.0.

## 3. Examples <a name='example'></a>

Engineered Region might represent a DNA component containing both a promoter and a CDS.

Composite could then be used to link to a sub-diagram showing the two subcomponents.

## 4. Backwards Compatibility <a name='compatibility'></a>

The "User Defined" rectangle will be deprecated, then removed.

## Copyright <a name='copyright'></a>

<p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    <img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />
  </a>
  <br />
  To the extent possible under law,
  <a rel="dct:publisher"
     href="sbolstandard.org">
    <span property="dct:title">SBOL developers</span></a>
  has waived all copyright and related or neighboring rights to
  <span property="dct:title">SEP V009</span>.
This work is published from:
<span property="vcard:Country" datatype="dct:ISO3166"
      content="US" about="sbolstandard.org">
  United States</span>.
</p>

**Comment by cjmyers** [comment]
This looks good to me.

**Comment by JS3xton** [comment]
Note: significant discussion on this topic has already occurred in [SEP V006](https://github.com/SynBioDex/SBOLv-realizations/issues/11).

---

> SBOL Visual Version: 1.1

I believe this should target SBOLv 2.0.

(Note: a discussion on the appropriate version was already started [here](https://github.com/SynBioDex/SBOLv-realizations/issues/11#issuecomment-332999947))

---

>The rectangle will also be eventually removed from Unspecified.

> The Rectangle alternative will be deprecated and given RECOMMEND NOT status for Unspecified in SBOL Visual 1.1, then removed entirely in SBOL Visual 2.0.

> The "User Defined" rectangle will be deprecated, then removed.

I will re-raise what I raised [here](https://github.com/SynBioDex/SBOLv-realizations/issues/11#issuecomment-333242644) and say:

1. The [Unspecified glyph](https://github.com/SynBioDex/SBOLv-realizations/tree/4df5efc9042894df4340df93cabfd817ed50f029/Glyphs/unspecified) is *new* (i.e. not currently present in the specification); I think we should simply introduce it with *no* specified alternatives (i.e. this SEP removes the rectangle glyph as a supported alternative for the [Unspecified glyph](https://github.com/SynBioDex/SBOLv-realizations/tree/4df5efc9042894df4340df93cabfd817ed50f029/Glyphs/unspecified) and supersedes [SEP V003](https://github.com/SynBioDex/SBOLv-realizations/issues/6), which declared the rectangle glyph as a valid alternative for the [Unspecified glyph](https://github.com/SynBioDex/SBOLv-realizations/tree/4df5efc9042894df4340df93cabfd817ed50f029/Glyphs/unspecified)) rather than try to communicate that it has a deprecated alternative that will eventually be removed. I'm also not familiar with the "RECOMMEND NOT status"; isn't *everything* RECOMMENDED NOT that isn't RECOMMENDED or an accepted ALTERNATIVE?
2. I don't understand precisely what "deprecation" means in the SBOL Visual context. How does that get realized?

**Comment by cjmyers** [comment]
I strongly want this to be part of the next release.  I don’t care too much the version number, but I want to get rid of rectangle for unspecified as soon as possible.

**Comment by jakebeal** [comment]
I believe all of this is likely to be made moot by the likelihood of skipping SBOL 1.1 and going straight to SBOL 2.0, if we can get SEP V009 and SEP V010 passed.

**Comment by jakebeal** [comment]
Accepted and integrated, and thus closed per SBOL procedure in updated SEP 001.
