### ISSUE TITLE
SEP V012: Stop Codons

### ISSUE THREAD

**Issue by chofski** [SynBioDex/SBOL-visual#41]
This SEP proposes an explicit way of representing stop codons (useful if this feature needs to be highlighted). I have included two variants based on discussions on the mailing list.

Full proposal is at: https://github.com/SynBioDex/SBOL-visual/blob/develop/SEPs/SEP_V012.md

**Comment by jakebeal** [comment]
Thank you, Tom.

Two questions:

1. Are you recommending that _both_ of these glyphs by adopted, or are you looking for the community to come to consensus on one of the two? Unless there is a strong reason to go for both, I would suggest we aim to come to consensus on one of the two, because it is generally preferable to limit the number of approved variants (increased coherence, reserved alternatives).
2. In the prior discussion, my impression had been that the cross went all the way to the corners, and I personally prefer that to the disconnected cross version that is now being shown. Can we add that as a potential option as well, or do you have a reason to recommend against it?

**Comment by jakebeal** [comment]
On a side note: per [GitFlow](https://datasift.github.io/gitflow/IntroducingGitFlow.html) development protocol (as noted in the top-level README), while the SEP should be on the develop branch the new glyphs should be on a feature branch, not develop.  I have made that adjustment, putting the stop codon draft glyphs into https://github.com/SynBioDex/SBOL-visual/tree/feature/stop-codon and updating the links in the SEP.

**Comment by chofski** [comment]
OK, I'll make the revision. I'd suggest the cross glyph as it is simpler and will extend the ends to reach the box. Apologies about not following branch conventions... I'm new to the GitFlow approach.

**Comment by jakebeal** [comment]
No criticism, just gentle adjustment. :-)

I like the cross version too; let's see if any voices get raised for the alternatives.

**Comment by JS3xton** [comment]
I suppose I will jump in for the alternative. The cross glyph evokes a Cleavage Site stem-top glyph to me (the only difference being the bounding box as far as I can tell). As such, I prefer the asterisk over the cross. I would also lobby for inclusion of a symmetric 8-pointed asterisk alternative, because that's how I usually draw asterisks by hand.

Also, is there a good reason to employ the DNA stem over the RNA stem for this glyph?

**Comment by chofski** [comment]
Very good points by all. It makes sense to have it for both DNA and RNA as they are encoded in these substrates. I don't actually have a preference whether it is a cross or asterisk – @jakebeal are you happy to go with the asterisk, or are you still in favour of the cross?

**Comment by jakebeal** [comment]
On cross vs. asterisk --- I think @JS3xton  makes a good point, and I am happy to go for the asterisk. I will also note that if we specify that the shape is an asterisk, then we need note consider 5-pointed vs. 6-pointed vs. 8-pointed --- all are "font level style differences" covered by the definition.

Regarding DNA vs. RNA stem: again @JS3xton brings up a good point. If we follow the general semantics of stem-top glyphs, then RNA stem would make sense as stop codon.  DNA stem would then mean Transcription End Site (SO:0000616).  No protein stem would be defined at this time.

**Comment by jakebeal** [comment]
@chofski Since we seem to have reached a point of reasonable consensus, can you please update the SEP accordingly? I'd like to then get both this and SEP V011 moved for a vote together.

**Comment by chofski** [comment]
I will make the updates. My only comment is that I'm not convinced that site should be defined for the DNA stem as the SEP is concerned solely with stop codons and not related to transcription.

**Comment by jakebeal** [comment]
I was suggesting that we expand to include transcription end site as well as stop codons.
How about including that as an option for people to discuss and vote on?
I'll be fine if people decide that's a bridge too far and vote not to do transcription, but I think it's a consistent generalization and would like to see if others agree in the wider community.

**Comment by chofski** [comment]
I've updated the SEP and after checking the biopolymer location symbols, updated them to be compatible. I've also changed the SEP from stop codons, to end points of transcription and translation, which I feel better captures the actual meaning.

**Comment by jakebeal** [comment]
Look great!  I adjusted slightly for archival purposes (linking the glyphs to the permanent commit since the branch will eventually go away; adding the discarded variants to the discussion section).

I believe this should now be ready for a vote, and will propose such on the list.

**Comment by jakebeal** [comment]
Accepted and integrated, and thus closed per SBOL procedure in updated SEP 001.

**Comment by veghp** [comment]
Further to this glyph, the original proposal intention was to introduce precision: _"denoting the end points of transcription (i.e. end of a transcript) and translation (i.e. start of a stop codon)."_

The associated SO terms for translation stop site are: SO:0000319 Stop Codon and [SO:0000327](http://www.sequenceontology.org/browser/current_release/term/SO:0000327)

> Definition:	The last base to be translated into protein. It does not include the stop codon.

The second SO term specifically does not include the STOP codon. Is this intentional? Does this mean the glyph marks the _boundary_ between the last translated codon and the stop codon -- and not these codons/nucleotides?

Edit: to clarify the above, the SBOL Visual doc calls it Stop Site and Translation End Point, which can be confused with the SO:0000327 synonyms "coding end, translation termination site, translation_end".

**Comment by jakebeal** [comment]
@veghp There are a number of cases, including this one, where there is intentionally a one-to-one mapping from sequence ontology to glyph but a one-to-many mapping from glyph to sequence ontology, with the idea that it should be able to be made clear in context. The definition of what counts as a "promoter" is another nice example of that, even though there is only one SO term there. 

Is this causing trouble for you? If so, there is the potential to add recommendations or new more specific glyphs.

**Comment by veghp** [comment]
Thank you for the clarification. I summarise it for future reference; the glyph can mean any of the below (and possibly more):

```
   S  *
..TCATAA..
    -    The last base to be translated into protein. (SO:0000327 = coding_end)
     --- a set of three nucleotides that indicates the end of information for protein synthesis.
     -   In genomic sequence, a stop codon may be only one
     --  or two nucleotides where the additional nucleotides are provided in the RNA via polyadenylation.
         (SO:0000319 = stop_codon)
```

No issue whatsoever. We have a set of [glyphs as a CSS library](https://github.com/Edinburgh-Genome-Foundry/SBOL-Visual-CSS), which is currently [being updated](https://github.com/Edinburgh-Genome-Foundry/SBOL-Visual-CSS/pull/1) by Matheo and we're considering what filename should this glyph have.

**Comment by jakebeal** [comment]
All of those sound reasonable to me! 

For naming the glyph, I would suggest mirroring the file names that are used in this repository, just so that it's easier to do automated checking. In this case, that would be [transcription-end.svg](https://github.com/SynBioDex/SBOL-visual/blob/master/Glyphs/SequenceFeatures/stop-site/transcription-end.svg) and [translation-end.svg](https://github.com/SynBioDex/SBOL-visual/blob/master/Glyphs/SequenceFeatures/stop-site/translation-end.svg)

**Comment by shyambhakta** [comment]
Stop codons can be regarded as four nucleotides, based on these studies: [[1]](https://doi.org/10.1093/nar/18.8.2079
) [[2]](https://doi.org/10.1046%2Fj.1365-2958.1996.6391352.x) [[3]](https://doi.org/10.1139/o95-118)

In eukaryotes, even more context may matter: [[4]](https://doi.org/10.1134/S0026893320050088)
Though this would make a stop codon + context mapping sometimes overlap with the polyA tail.

And there's good reason why shrewd designers use specific double stop codons in bacteria. My norm is TGATAAT for the best double-tetranucleotide stop. I remember iGEM parts used to often have TAATAA. [[5]](https://doi.org/10.1016/S0014-5793(02)02301-3)

At minimum, I'd think a double stop sequence should qualify for a single glyph, since its intent and function is for stimulating a single translation process to stop. At most, vaguest, and focusing on engineering-intent, it could be "sequence at end of a CDS, designed to terminate translation". Granted, this would extend the SO definition it seems.
