### ISSUE TITLE
Vertical Orientation Option

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-visual#49]
From @jfarlow

Is there a standard for vertical orientation of the SBOL visual language?

It seems like a visual language should be compatible with the vertical scrolling patterns commonly used on a computer screen. With more than just a few components it becomes impossible to annotate a SBOL map without having a user either scroll horizontally (a terrible user interface pattern), or have 'rows' which must be kept track of and would be both jarring to the user, and difficult to implement in a responsive way.

Has there been any thought to how the visual language can be adopted in a vertical manner so that theoretically a massively annotated plasmid, or even small chromosome could be reasonably represented on a computer screen?

**Comment by bbartley** [comment]
When you are viewing DNA at this high level and the features are densely concentrated, I think the best you might do is represent the DNA as a line with individual features represented by generic tick marks, dots, or boxes.  I think only at a mid-scale, when features are not so densely clustered, does it make sense to use SBOLv symbols.
I think the Geneious editor does something like this.  At different scales of zoom, the DNA sequence is represented using different graphic representations.  At the lowest level, you see individual nucleotides, and at the highest level something like a line with generic features.  Thats my memory anyway.
Representing symbols as rows is not necessarily a bad option either.  It's not always ideal, but I wouldn't describe it as "jarring".
Bryan

    On Friday, June 15, 2018, 1:20:32 PM EDT, cjmyers <notifications@github.com> wrote:  
 
 
From @jfarlow

Is there a standard for vertical orientation of the SBOL visual language?

It seems like a visual language should be compatible with the vertical scrolling patterns commonly used on a computer screen. With more than just a few components it becomes impossible to annotate a SBOL map without having a user either scroll horizontally (a terrible user interface pattern), or have 'rows' which must be kept track of and would be both jarring to the user, and difficult to implement in a responsive way.

Has there been any thought to how the visual language can be adopted in a vertical manner so that theoretically a massively annotated plasmid, or even small chromosome could be reasonably represented on a computer screen?

**Comment by jakebeal** [comment]
Currently, we explicitly recommend against reorienting the backbone except to illustrate structure (e.g., circularity). This follows the convention that I have seen in publications --- I have never seen anyone deal with extremely long constructs in a way other than just being long, omitting details, or breaking into rows. Furthermore, Ido not personally have any good ideas for how to do so at present.

If @jfarlow or anyone else has good suggestions, however, I'm happy to hear them and consider for inclusion into the standard.

**Comment by jakebeal** [comment]
As this has been lying fallow for a year with a state of "probably we don't want to change anything", I am going to close it.  It can be reopened if anyone really wants a vertical option.
