### ISSUE TITLE
SEP V016: Introns and Polypeptide Regions

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#63]
Coding sequences are often annotated to note specific regions, tags, or introns. This SEP proposes to adopt new glyphs to supposed such annotation derived from the ones used by the UPV Golden Braid repository.

Read the full SEP at: https://github.com/SynBioDex/SBOL-visual/blob/master/SEPs/SEP_V016.md
Draft branch at: https://github.com/SynBioDex/SBOL-visual/commit/2b4e91f1c11e792714b39b3a075e18782003ae84

**Comment by shyambhakta** [comment]
The N-terminal tag specifically being recommended to _not_ be a chevron, instead to be separated from the rest of the CDS with a vertical line **(A)**, has a basis in making small N-terminal peptide tags distinct from other major domains in the CDS, but I don't like that the same recommendation isn't made for C-terminal tags, which aren't significantly less common. It makes the recommendation seem inconsistent/incomplete. Or maybe this is just pedantry.

I see three solutions: 
1. Demarcating C-terminal tags from the rest of the CDS likewise with a vertical line **(B)**.

2. Require demarcating _any_ domain with vertical lines, lending clear meaning to the beginning and end of the chevron shape as start and stop codons for multi-domain CDSs **(C)**. 
Otherwise, in (A/B) it's not clear to me how the chevron ">" versus line "|" borders within a CDS glyph would be distinguished in meaning. This would, however, erase the interlocking chevron metaphor of fused domains. Might then just divide the original non-chevron CDS glyph up with lines. Or stick with all chevrons **(E/F)**.

3.  Distinguish native versus synthetic domain boundaries: ">" as native, evolved boundaries of domains, and "|" as synthetic boundaries made by translational fusion **(Da)**. Or maybe vice-versa **(Db)**.
For example, in (C) and (Dab), the white domain might be GFP, and the pink and purple domains are respectively the native DNA-binding and regulatory domains of TetR. And the cyan and yellow tags are synthetic, as before.

I like that Db preserve the interlocking chevron metaphor of fused domains, while adding information about native versus synthetic domain fusions. The chevron better evokes a synthetic fusion, making Db preferred over Da. However, N- and C-terminal tags aren't specifically distinguished from other domains like the _gfp_ tag.

Any thoughts?

![image](https://user-images.githubusercontent.com/5035245/56402984-24aadc00-6225-11e9-9167-79521437e02d.png)

**Comment by jakebeal** [comment]
The key thing that I was struggling with is the fact that the base CDS icon is a pentagon:
![image](https://github.com/SynBioDex/SBOL-visual/blob/master/Glyphs/cds/cds-specification.png?raw=true)

I like the idea of symmetrically using chevron for all domains.  That does quite nicely for domains in the middle and at the C-terminal. At the N-terminal, though, it's just not flat, so it's either stuck inside the line (leaving one to wonder at the meaning of the triangle) or sticking outside the line (making a CDS no longer a pentagon).

**Comment by DavidZong** [comment]
Either have all of the dividing regions be vertical bars or chevrons but not a mixture of the two. I think chevrons are better. I like example Db with the vertical bar in between the pink and orange region be a chevron.

Though all of this could potentially get messy if features need to be precisely scaled to length.

**Comment by shyambhakta** [comment]
Ok, so David likes the new option **(E)**.
That is the simplest way to go.

The boundary still doesn't match the original pentagonal CDS glyph.
Would new option **(F)** be too inconsistent, in that the first domain has a flat front and all subsequent have triangular fronts? The specification may be described as _dividing_ the original CDS glyph into chevrons, versus concatenating a pentagonal CDS glyph with one or more chevron domain glyphs.

**Comment by jakebeal** [comment]
I could definitely get behind (F) as well.  I like the internal consistency, while still conforming with the CDS glyph and also making a clear visual distinction between domains on a CDS vs. two separate CDS regions.

**Comment by jatk** [comment]
I like (F) because it's consistent with the original CDS glyph, but i think the domains should be divided by straight lines as in (C). The chevron look, while aesthetically pleasing could cause one to misinterpret the glyph as several CDS laying on top of one another

**Comment by jakebeal** [comment]
@jatk On straight vs. chevron: one might say that in (C) there is the same potential for confusion with regards to the rectangular Engineered Region glyph?

**Comment by shyambhakta** [comment]
So @jatk likes new option **(G)**.

To summarize, **(E)** looks like it could be interpreted as tandem or overlapping CDSs, though that's kind of the point for the domain glyph, to emulate concatenated CDSs. But it would be nice to have the original pentagonal CDS outline like in (F/G).
In the case of operons, where CDSs are often tandem or slightly overlapping, the implicit space in tandem CDSs with style **(E)** (below) may be misleading, unless the beginning of the sequence maps to the point where the glyph _touches_ the line, not where it hangs over it, in which case tandem CDSs of style (E) would be indistinguishable from domains of the same CDS. 

**(F)** and **(G)** below make a better distinction of tandem CDSs vs domains in that a CDS must start with a straight line, never found inside a CDS unless another distinct CDS is starting.
But **(F)** _could_ still look like CDSs are stacked from 5′-most at the top to 3′-most at the bottom, hiding the straight lines they begin with. But @jakebeal, can this be addressed by recommending overlapping CDSs not hide one another's outlines? Or staggering the glyphs or something?

**(G)** could only look like one CDS as intended, but could be interpreted as containing engineered regions, whose glyph is a box. Also with (G), there is no specification for a stand-alone domain glyph, because it can't be a box. But with (E) and (F), it's intuitive to use a chevron as a distinct domain glyph, too.

I think **(F)** has the highest score currently.

![image](https://user-images.githubusercontent.com/5035245/56402961-1066df00-6225-11e9-9680-8e57d3b252fe.png)

**Comment by shyambhakta** [comment]
To address the distinction between truly overlapping CDSs and domains within a CDS, here's an example of a real set of CDSs from the RSF1010 replication origin. Also relevant to Issue #57.
(Q): superimposed, no fill.
(R/S): vertically scaled, centered or bottom-aligned.  (R) requires more size disparity between CDSs to get enough space above and below frontmost CDSs relative to ones behind. So (S) is preferable, perhaps.
(T/U): vertically shifted. Doesn't require glyph scaling, thus easiest. 

All options seem to be least ambiguous if the CDS glyphs are stacked such that the right ends are exposed, as in (T) vs (U).

![image](https://user-images.githubusercontent.com/5035245/56408318-837a5080-6239-11e9-8b2f-1d13556b0aef.png)

**Comment by jakebeal** [comment]
@shyambhakta Thank you for all of your careful thought and nice illustrations here.  I agree with your assessment that (F) seems to be the version that's best capturing all of the requirements.

For the representation of overlapping CDSs, I will note that we explicitly avoid setting _requirements_ regarding positioning and scaling of any glyph, to allow for freedom of expression.  We can certainly use RECOMMEND to suggest best practices, however, and in that regard I would suggest that R/S/T/U are all good approaches with no particular reason to force a choice between them a priori.  I would thus suggest we add something like this to the notes on both CDS and domain:

> To clearly distinguish overlapping CDS regions from domains, it is RECOMMENDED that overlapping CDS glyphs be scaled and/or offset vertically, such as in these examples: [put R,S,U in]

**Comment by JS3xton** [comment]
I don't think any of these options should (in theory) be confused with the Engineered Region glyph because the Engineered Region glyph sits _atop_ the DNA line whereas these are all vertically centered _on_ the line. That being said, I know folks who still like to illustrate the CDS glyph atop the DNA line, so it's probably best not to rely on that vertical positioning as a distinguishing factor.

That said, I also favor (F), followed by (G).

Can I then combine domains / Polypeptide Regions with Introns? e.g.

![cds](https://user-images.githubusercontent.com/2179825/56699889-16ddd680-66bd-11e9-981a-0a44eb9e3000.png)

This illustrates a CDS with two domains (blue d1 and red d2) as well as some unstructured regions (white CDS/chevrons). d2 spans two introns.

I feel like introns should break the outline of the CDS glyph. Maybe their edges should also be made to fit together like puzzle pieces upon excision of the intron? e.g.

![cds2](https://user-images.githubusercontent.com/2179825/56700050-d599f680-66bd-11e9-9e84-ba67df758d10.png)

**Comment by jakebeal** [comment]
@JS3xton Very nice!  I think that your illustrations show very nicely how these can be combined into a coherent and unambiguous language!

I like your suggestion regarding flipping the left side of intron as well.  I will update the SEP to reflect all of these comments.

**Comment by JS3xton** [comment]
Another thought: what happens if a domain boundary and an intron boundary coincide? Use the intron boundary and rely on color to differentiate domains? e.g.

![cds3a](https://user-images.githubusercontent.com/2179825/56751508-dc6f4a80-674b-11e9-90d9-ceb36f856b46.png)

which could be recoded as:

![cds3b](https://user-images.githubusercontent.com/2179825/56751655-38d26a00-674c-11e9-880f-4142bff21fb6.png)

**Comment by jakebeal** [comment]
That looks quite reasonable to me.

Thanks,
-Jake

**Comment by hasanbaig** [comment]
@jakebeal are the recommendations incorporated in the SEP ? Is it ready for voting ?

**Comment by jakebeal** [comment]
@hasanbaig Not yet; I haven't gotten a chance.  If somebody else beats me to it, that's fine too.

**Comment by castillohair** [comment]
I'm late to the party, but I vote for Shyam's option F, followed by G.

For the record, I have a paper in press where I chose to represent, before this issue opened, several sfgfp-tagged proteins using something that turned out to be identical to option G  (I also got to use the [genomic locus glyph!](https://github.com/SynBioDex/SBOL-visual/tree/master/Glyphs/chromosomal-locus)). I don't know how much weight is being placed on precedent, but I thought I would mention this just in case.

**Comment by jakebeal** [comment]
Hi, folks: I've updated the SEP, embracing option F and the compositional options for introns.
See update SEP at: https://github.com/SynBioDex/SBOL-visual/blob/master/SEPs/SEP_V016.md
If people are happy, we can move this forward to vote.

**Comment by jakebeal** [comment]
I haven't heard any objections, so I'm going to move for a vote.

**Comment by graik** [comment]
I just looked at it now -> I like the intron symbols but I think using the chevron for protein features is quite misleading. Option G in @shyambhakta comment further above would be the much cleaner solution. The chevrons look a lot like consecutive CDS to me. This matches @castillohair 's comment. A simple sub-division of a CDS region with rectangles is what I see most often when sub-features of a gene are annotated.

**Comment by jakebeal** [comment]
@graik The illustration for Option F shows shows show consecutive CDS is distinct from protein features (essentially via the flat vs. bent edge), even if it might be more subtle than some might want.  Unfortunately, in Option G there is no way to distinguish between protein domains and  Engineered Region glyphs.

**Comment by graik** [comment]
@jakebeal do we need this distinction? We are looking at engineered proteins here so a domain within an engineered protein is kind of an engineered region just as well, isn't it? :thinking:

**Comment by jakebeal** [comment]
We do, I'm afraid:
http://www.sequenceontology.org/browser/current_release/term/SO:0000804
and 
http://www.sequenceontology.org/browser/current_release/term/SO:0000188
are quite different semantics, and get used in very different contexts in display.

**Comment by graik** [comment]
Well, first of all, sorry for bringing it up this late... 
"Engineered region" also includes "engineered tag" which is a polypeptide region. So there is bound to be cases of confusion. Also, can engineered region (rectangle) be combined with the chevron in the same CDS? It should be possible but I don't see how the two can be put next to each other without breaking the CDS outline. I guess, we simply have to see how this all plays out in practice.

**Comment by jakebeal** [comment]
All changes are now merged.
